name: generate pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kywy12
          template: classic
          base: ""
          filename: github-metrics-pacman.svg
          plugin_pacman: yes
          plugin_pacman_chart: yes
